### PR TITLE
Update closure compiler to v20200719

### PR DESCRIPTION
**Pull request by xvilo**
This updates closure compiler to v20200719. It compiles our code base with minimal changes (some closure checks have become more strict). With closure library version: 20200315.0.0

This version is probably the latest version that is currently support with plovr. As they are moving away from `goog.require()`. We would need some more work to support new imports. However, I'm not skilled enough to easily fix this.

### CODE REVIEW

**Comment by xvilo** [comment]
@nicks can you review and merge this? I can will create a lib update mr later on to version `20200315.0.0` as this is the last known working version :)

**Comment by xvilo** [comment]
I can supply a working jar if needed :)

**Comment by nicks** [comment]
Hi @xvilo ! I'll try to get to this later tonight.

I haven't been following closure's strategy for goog.require / better import support deeply, and what it would even take to support it

**Comment by xvilo** [comment]
That's fine! Both PRs can be merged and are in a working state. I have created an issue to discuss compatibility moving forward, so let's keep that discussion there 👍

**Pull request merged**
