### PR TITLE
Update Closure Library to v20190929

### PR DESCRIPTION
**Pull request by xvilo**

### CODE REVIEW

**Comment by xvilo** [comment]
Is this how we update closure @nicks?

**Comment by xvilo** [comment]
@nicks it would be great if this could be merged too, we can not build closure yet with these changes, but i'll push all fixes after this merge.

**Comment by nicks** [comment]
hmmm...this doesn't seem to pass the tests?

**Comment by xvilo** [comment]
That's correct @nicks, there are some changes in the compiler too. You can try the compiler MR

**Comment by xvilo** [comment]
Seems you did it yourself, closing this MR

**Comment by nicks** [comment]
yep, thanks! i wanted to tweak a few things

**Pull request closed without merging**
