### PR TITLE
Update closure compiler v20181125

### PR DESCRIPTION
**Pull request by xvilo**
- update closure compiler to v20181125
- change visibility of `getDiagnosticGroups` to public to match closure compiler
- Update NPM version

### CODE REVIEW

**Comment by xvilo** [comment]
Builds successfully here, could this be reviewed and merged?

**Comment by xvilo** [comment]
We are currently using this in production right now

**Comment by nicks** [comment]
thanks! but why only update to v20181125?

**Comment by xvilo** [comment]
There are currently more/other issues when updating to a higher version, currently working on it. But want to do it in smaller bits. A small update is better then no update right now

**Comment by nicks** [comment]
ok!

**Comment by xvilo** [comment]
@nicks can you also update the npm package? That would be highly appreciated: https://www.npmjs.com/package/plovr

**Comment by nicks** [comment]
will do! need to check out the repo and run some tests, and it's taking a bit.

**Comment by xvilo** [comment]
Great! Thanks for the swift responses, it's appreciated.

**Comment by nicks** [comment]
Ugh, unfortunately I'm travelling today and the wifi has been very unreliable. Trying to build + publish keeps failing. Will keep trying but may have to give up and try again tomorrow.

**Comment by xvilo** [comment]
Ah, I see it breaks now. I probably forgot to push one of the fixes to this repo. 
I had some trouble keeping everything separated between our internal repo and this one.

**Comment by xvilo** [comment]
@nicks, seems everything is in order with current master, here is a build: https://sschilder.stackstorage.com/s/XD6NQexYJNXlYh3

**Comment by nicks** [comment]
unfortunately, i no longer have access the the plovr npm package. it seems like Medium took it over :\

**Pull request merged**
