### PR TITLE
Fix for issue: Sourcemap broken #29

### PR DESCRIPTION
**Pull request by maximilianvoss**
added some new configuration options:  
* __source-map-base-url__: to add a base URL where the js code finds it source map
* __module-source-map-name__: to make the source map name configurable (%s for module name). This was done before by using sourceMapPath + "_" + moduleName

Fixed the testdata/modules/build-module-example.sh script as it was still building with ant.

### CODE REVIEW

**Comment by maximilianvoss** [comment]
sorry was easier to me to create a new pull request as I mixed up the branches a little. Have some more I'd like to adapt.

**Comment by nicks** [comment]
thanks!

**Comment by nicks** [comment]
actually i'm going to change the API around a bit so that there's a `source-map-output-name` that works for both modularized and unmodularized code

**Comment by maximilianvoss** [comment]
Makes a lot of sense

**Pull request merged**
