### PR TITLE
js input name

### PR DESCRIPTION
**Pull request by dimonka83**
There are several problems in some classes with absolute (/), subdirectories (../) and current dir (./) chars in file names. There are many "hacks" to resolve them. But it's better to make all names in one style. For future using restful handlers it's better to use relative names, subdirectories replaced with $$/ as before.

### CODE REVIEW

**Comment by dimonka83** [comment]
PIng guys. Will somebody review this pull?

**Comment by nicks** [comment]
I don't understand what problem this PR is trying to solve. There's a method `nomalizeName`, but it has no comments describing what "normalize" means or what the expected behavior is.

**Comment by imirkin** [comment]
iirc (some of) the testdata in plovr is able to trigger this issue,
depending how you run it. i was running into it with my localization
patches (which i guess i should rebase and resubmit... again)

**Comment by nicks** [comment]
(it would also be helpful if there was a test that demonstrated what problem this PR is solving, such that the test fails before this PR and passes after)

**Comment by dimonka83** [comment]
At first, for example, you can change `inputs` from `example/main.js` to `../demo/example/main.js` in `demo-config.js` file. Then run `http://localhost:9811/demo/advanced-demo.html`. Compilation is ok, but sourcemap is wrong. In `sources` section of sourcemap you see `/input/demo/../demo/example/main.js`, but expected to see `/input/demo/$$/demo/example/main.js`. Finally, you can not see the source of `../demo/example/main.js` in devtools because browser try to load `http://localhost:9810/input/demo/example/main.js`.

At second, for example, in far far away future you will want to change `ViewFileHandler` to restful. You should make changes like in `InputFileHandler` (replace `$$` to `..`, dublicate hacks to find input, etc). The better way is move that functionality in another place. It's just done in this PR with method `normalizeName`. Maybe method name is not good, i borrow it from `URI.normalize`.

About tests. I will try it.

**Comment by xvilo** [comment]
Can we close this @nicks/@dimonka83?

**Comment by xvilo** [comment]
Can we close this @nicks / @dimonka83?

**Comment by nicks** [comment]
closing as stale

**Pull request closed without merging**
