### PR TITLE
fix all the tests

### PR DESCRIPTION
**Pull request by nicks**

### CODE REVIEW

**Comment by xvilo** [comment]
@nicks How did you run these tests?

**Comment by nicks** [comment]
buck test ...

**Comment by xvilo** [comment]
Weird, that doesn't work here. Never got it working:

```
$ buck test ...
Not using buckd because watchman isn't installed.
When parsing //../..:..: incorrect base name: //../...
```

So I always thought it might have been old or bad documentation. However the following does work:

```
$ buck test :test
Not using buckd because watchman isn't installed.
Parsing buck files: finished in 2.8 sec
Creating action graph: finished in 2.0 sec
Building... 3.3 sec (97%) 136/139 jobs, 4 updated
```

**Comment by rgpower** [comment]
Maybe this way:

buck fetch ...
buck test

**Comment by xvilo** [comment]
The same, for some reason Buck has never been able to parse `...` correctly @rgpower.

log:

```
$ buck fetch ...
Not using buckd because watchman isn't installed.
When parsing //../..:..: incorrect base name: //../...
```

I always did: `buck fetch //third-party/...` which does work here

**Comment by rgpower** [comment]
This worked for me on my mac (that buck docker image is bit big (~1GB ish)
so it takes a while to download)

cd plovr
docker run --rm -it -e HOME -v /Volumes:/Volumes:delegated -w $PWD
praqma/native-buck:latest buck fetch ...
docker run --rm -it -e HOME -v /Volumes:/Volumes:delegated -w $PWD
praqma/native-buck:latest buck test ...

hth,
Rick

PS: output was

Not using buckd because watchman isn't installed.
Parsing buck files: finished in 3.2 sec (100%)
Creating action graph: finished in 0.7 sec (100%)
Building: finished in 34.7 sec (100%) 175/175 jobs, 66 updated
  Total time: 38.6 sec
Testing: finished in 01:21.3 min (85 PASS/0 FAIL)
RESULTS FOR //:test
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.AbstractGetHandlerTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed
org.plovr.AbstractJsInputTest
PASS      5.8s  2 Passed   0 Skipped   0 Failed
org.plovr.CoffeeScriptCompilerTest
PASS      1.3s  3 Passed   0 Skipped   0 Failed
org.plovr.CompilationCacheTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.CompilationServerTest
PASS      2.7s  5 Passed   0 Skipped   0 Failed   org.plovr.CompilationTest
PASS      5.5s  2 Passed   0 Skipped   0 Failed
org.plovr.CompileRequestHandlerTest
PASS      5.9s  4 Passed   0 Skipped   0 Failed   org.plovr.ConfigParserTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.ConfigPathTest
PASS    <100ms  5 Passed   0 Skipped   0 Failed   org.plovr.ConfigTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.DepsJsInputTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed   org.plovr.FileUtilTest
PASS    <100ms  5 Passed   0 Skipped   0 Failed   org.plovr.GsonTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.IndexRequestHandlerTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed
org.plovr.InputFileHandlerTest
PASS      5.5s  2 Passed   0 Skipped   0 Failed   org.plovr.IntegrationTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed   org.plovr.JsSourceFileTest
PASS      4.2s  1 Passed   0 Skipped   0 Failed   org.plovr.ListHandlerTest
PASS      4.6s  3 Passed   0 Skipped   0 Failed   org.plovr.ManifestTest
PASS      2.8s  3 Passed   0 Skipped   0 Failed   org.plovr.ModuleConfigTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.ModulesHandlerTest
PASS      3.3s  1 Passed   0 Skipped   0 Failed
org.plovr.NameCollisionTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.ResourceReaderTest
PASS     13.2s  1 Passed   0 Skipped   0 Failed   org.plovr.SizeHandlerTest
PASS    <100ms  3 Passed   0 Skipped   0 Failed
org.plovr.SoyFileOptionsTest
PASS     261ms  2 Passed   0 Skipped   0 Failed   org.plovr.SoyFileTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed   org.plovr.TestHandlerTest
PASS     22.7s  2 Passed   0 Skipped   0 Failed
org.plovr.TypeScriptCompilerTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.ViewFileHandlerTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed
org.plovr.i18n.PseudoTranslatorTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.soy.server.RequestHandlerSelectorTest
PASS    <100ms  2 Passed   0 Skipped   0 Failed
org.plovr.soy.server.SoyRequestHandlerTest
PASS    <100ms  6 Passed   0 Skipped   0 Failed
org.plovr.util.GsonUtilTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.util.HttpExchangeUtilTest
PASS    <100ms  8 Passed   0 Skipped   0 Failed   org.plovr.util.PairTest
PASS    <100ms  1 Passed   0 Skipped   0 Failed
org.plovr.util.VersionUtilTest
TESTS PASSED

**Comment by rgpower** [comment]
You may have to change the commands to read like this, my mac has custom user home volume.
```
cd plovr
docker run --rm -it -e HOME -v /Volumes:/Volumes:delegated -v /Users:/Users:delegated -w $PWD praqma/native-buck:latest buck fetch ...
docker run --rm -it -e HOME -v /Volumes:/Volumes:delegated -v /Users:/Users:delegated -w $PWD praqma/native-buck:latest buck test ...
```

**Pull request merged**
