### PR TITLE
Update to latest closure jars

### PR DESCRIPTION
**Pull request by rgpower**
Hey @nicks ,

I am hoping you will consider this pull request which updates plovr to use the latest closure-related jars from Maven central, in particular:

- https://mvnrepository.com/artifact/com.google.closure-stylesheets/closure-stylesheets/1.5.0
- https://mvnrepository.com/artifact/com.google.template/soy/2017-08-08
- https://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20171023

These updates required some small changes to plovr src in order to
avoid use of removed/deprecated apis.

In particular: 

**closure-templates 2017-08-08 changes**

1.  accomodate recent soy updates around use of the soy autoescape mode 'deprecated-noncontextual' in plovr's own soy templates
1. accomodate soy command 'css' replaced in favour of new soy function 'css'
1. replace calls to soyData (now removed) with StringData.forValue since former function is now removed.
1. replace calls to now private ErrorReporterImpl with static builder function ErrorReporter.explodeOnErrorsAndIgnoreWarnings
1. replace usages of now private SoyMsg constructor with static builder SoyMsg.build

**closure-compiler v20171023 changes**

1. accomodate node.getType() replaced with node.getToken()
1. NodeTraversal.traverse deprecated in favour of NodeTraversal.traverseEs6
1. prettyPrint field now made private - use setter instead
1. accomodate isStrict changes in compiler config, enable users to configure via new 'strict-mode-input' (boolean) config opt
1. prefer LanguageMode.fromString over LanguageMode.valueOf since former normalizes the obsolete modes 'ECMASCRIPT6'  and 'ECMASCRIPT6_STRICT' into 'ECMASCRIPT_2015' (compatibility)
1. update input order in ConfigParserTest caused by new compiler version

**other:**

1. This pull request also removes closure-stylesheets from plovr and pulls it from Maven central.
1. Finally, reduce number of chrome complaints related to raw.soy's
use of document.write, by combining all of the separate calls into
one jumbo call.
1. No changes were required for plovr to handle Google Stylesheet (gss) files using latest closure-stylesheets 1.5.0 jar.

### CODE REVIEW

**Comment by nicks** [comment]
thanks for doing this! let me poke around at it a bit

**Comment by nicks** [comment]
mostly looks good. a few minor issues:
- now there are a bunch of closure-library warnings? i think there's a mismatch between compiler version and library version that we'll need to reconcile
- the template auto-escaping stuff isn't quite right, because that code is printing js, not html
i'm going to try to make these changes myself and merge in a separate pr

**Comment by nicks** [comment]
ok, i merged this in parts and made the auto-escaping changes. it was a bit messier than i would have liked but it worked out ok

**Comment by rgpower** [comment]
Hey @nicks, thanks so very much for taking the time (and effort) to merge these updates.  I am honoured to have been able to make even a small contribution to plovr, as it has been so beneficial to me and my colleagues.

**Pull request closed without merging**
